# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: 'search'

  pool:
    vmImage: 'windows-2019'

  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python Version'
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
    workingDirectory: .

  - script: |
      pip install azure-core
      pip install -r requirements.txt
      python example.py 
    displayName: 'run tests'
    workingDirectory: .
