# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6320, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Airport
    from ._models_py3 import Answer
    from ._models_py3 import CivicStructure
    from ._models_py3 import ContractualRulesAttribution
    from ._models_py3 import ContractualRulesContractualRule
    from ._models_py3 import ContractualRulesLicenseAttribution
    from ._models_py3 import ContractualRulesLinkAttribution
    from ._models_py3 import ContractualRulesMediaAttribution
    from ._models_py3 import ContractualRulesTextAttribution
    from ._models_py3 import CreativeWork
    from ._models_py3 import EntertainmentBusiness
    from ._models_py3 import Entities
    from ._models_py3 import EntitiesEntityPresentationInfo
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import FoodEstablishment
    from ._models_py3 import Hotel
    from ._models_py3 import Identifiable
    from ._models_py3 import ImageObject
    from ._models_py3 import Intangible
    from ._models_py3 import License
    from ._models_py3 import LocalBusiness
    from ._models_py3 import LodgingBusiness
    from ._models_py3 import MediaObject
    from ._models_py3 import MovieTheater
    from ._models_py3 import Organization
    from ._models_py3 import Place
    from ._models_py3 import Places
    from ._models_py3 import PostalAddress
    from ._models_py3 import QueryContext
    from ._models_py3 import Response
    from ._models_py3 import ResponseBase
    from ._models_py3 import Restaurant
    from ._models_py3 import SearchResponse
    from ._models_py3 import SearchResultsAnswer
    from ._models_py3 import StructuredValue
    from ._models_py3 import Thing
    from ._models_py3 import TouristAttraction
except (SyntaxError, ImportError):
    from ._models import Airport  # type: ignore
    from ._models import Answer  # type: ignore
    from ._models import CivicStructure  # type: ignore
    from ._models import ContractualRulesAttribution  # type: ignore
    from ._models import ContractualRulesContractualRule  # type: ignore
    from ._models import ContractualRulesLicenseAttribution  # type: ignore
    from ._models import ContractualRulesLinkAttribution  # type: ignore
    from ._models import ContractualRulesMediaAttribution  # type: ignore
    from ._models import ContractualRulesTextAttribution  # type: ignore
    from ._models import CreativeWork  # type: ignore
    from ._models import EntertainmentBusiness  # type: ignore
    from ._models import Entities  # type: ignore
    from ._models import EntitiesEntityPresentationInfo  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import FoodEstablishment  # type: ignore
    from ._models import Hotel  # type: ignore
    from ._models import Identifiable  # type: ignore
    from ._models import ImageObject  # type: ignore
    from ._models import Intangible  # type: ignore
    from ._models import License  # type: ignore
    from ._models import LocalBusiness  # type: ignore
    from ._models import LodgingBusiness  # type: ignore
    from ._models import MediaObject  # type: ignore
    from ._models import MovieTheater  # type: ignore
    from ._models import Organization  # type: ignore
    from ._models import Place  # type: ignore
    from ._models import Places  # type: ignore
    from ._models import PostalAddress  # type: ignore
    from ._models import QueryContext  # type: ignore
    from ._models import Response  # type: ignore
    from ._models import ResponseBase  # type: ignore
    from ._models import Restaurant  # type: ignore
    from ._models import SearchResponse  # type: ignore
    from ._models import SearchResultsAnswer  # type: ignore
    from ._models import StructuredValue  # type: ignore
    from ._models import Thing  # type: ignore
    from ._models import TouristAttraction  # type: ignore

from ._entity_search_client_enums import (
    AnswerType,
    EntityQueryScenario,
    EntityScenario,
    EntityType,
    ErrorCode,
    ErrorSubCode,
    ResponseFormat,
    SafeSearch,
    XBingApisSDK,
)

__all__ = [
    "Airport",
    "Answer",
    "CivicStructure",
    "ContractualRulesAttribution",
    "ContractualRulesContractualRule",
    "ContractualRulesLicenseAttribution",
    "ContractualRulesLinkAttribution",
    "ContractualRulesMediaAttribution",
    "ContractualRulesTextAttribution",
    "CreativeWork",
    "EntertainmentBusiness",
    "Entities",
    "EntitiesEntityPresentationInfo",
    "Error",
    "ErrorResponse",
    "FoodEstablishment",
    "Hotel",
    "Identifiable",
    "ImageObject",
    "Intangible",
    "License",
    "LocalBusiness",
    "LodgingBusiness",
    "MediaObject",
    "MovieTheater",
    "Organization",
    "Place",
    "Places",
    "PostalAddress",
    "QueryContext",
    "Response",
    "ResponseBase",
    "Restaurant",
    "SearchResponse",
    "SearchResultsAnswer",
    "StructuredValue",
    "Thing",
    "TouristAttraction",
    "AnswerType",
    "EntityQueryScenario",
    "EntityScenario",
    "EntityType",
    "ErrorCode",
    "ErrorSubCode",
    "ResponseFormat",
    "SafeSearch",
    "XBingApisSDK",
]
