# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6320, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Action
    from ._models_py3 import Answer
    from ._models_py3 import CreativeWork
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import Identifiable
    from ._models_py3 import QueryContext
    from ._models_py3 import Response
    from ._models_py3 import ResponseBase
    from ._models_py3 import SearchAction
    from ._models_py3 import SearchResultsAnswer
    from ._models_py3 import Suggestions
    from ._models_py3 import SuggestionsSuggestionGroup
    from ._models_py3 import Thing
except (SyntaxError, ImportError):
    from ._models import Action  # type: ignore
    from ._models import Answer  # type: ignore
    from ._models import CreativeWork  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import Identifiable  # type: ignore
    from ._models import QueryContext  # type: ignore
    from ._models import Response  # type: ignore
    from ._models import ResponseBase  # type: ignore
    from ._models import SearchAction  # type: ignore
    from ._models import SearchResultsAnswer  # type: ignore
    from ._models import Suggestions  # type: ignore
    from ._models import SuggestionsSuggestionGroup  # type: ignore
    from ._models import Thing  # type: ignore

from ._auto_suggest_client_enums import (
    ErrorCode,
    ResponseFormat,
    SafeSearch,
    ScenarioType,
    SearchKind,
    XBingApisSDK,
)

__all__ = [
    "Action",
    "Answer",
    "CreativeWork",
    "Error",
    "ErrorResponse",
    "Identifiable",
    "QueryContext",
    "Response",
    "ResponseBase",
    "SearchAction",
    "SearchResultsAnswer",
    "Suggestions",
    "SuggestionsSuggestionGroup",
    "Thing",
    "ErrorCode",
    "ResponseFormat",
    "SafeSearch",
    "ScenarioType",
    "SearchKind",
    "XBingApisSDK",
]
