# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6320, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Answer
    from ._models_py3 import CreativeWork
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import Identifiable
    from ._models_py3 import ImageObject
    from ._models_py3 import Images
    from ._models_py3 import MediaObject
    from ._models_py3 import Query
    from ._models_py3 import Response
    from ._models_py3 import ResponseBase
    from ._models_py3 import SearchResultsAnswer
    from ._models_py3 import Thing
    from ._models_py3 import WebPage
except (SyntaxError, ImportError):
    from ._models import Answer  # type: ignore
    from ._models import CreativeWork  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import Identifiable  # type: ignore
    from ._models import ImageObject  # type: ignore
    from ._models import Images  # type: ignore
    from ._models import MediaObject  # type: ignore
    from ._models import Query  # type: ignore
    from ._models import Response  # type: ignore
    from ._models import ResponseBase  # type: ignore
    from ._models import SearchResultsAnswer  # type: ignore
    from ._models import Thing  # type: ignore
    from ._models import WebPage  # type: ignore

from ._custom_image_search_client_enums import (
    ErrorCode,
    ErrorSubCode,
    Freshness,
    ImageAspect,
    ImageColor,
    ImageContent,
    ImageLicense,
    ImageSize,
    ImageType,
    SafeSearch,
    XBingApisSDK,
)

__all__ = [
    "Answer",
    "CreativeWork",
    "Error",
    "ErrorResponse",
    "Identifiable",
    "ImageObject",
    "Images",
    "MediaObject",
    "Query",
    "Response",
    "ResponseBase",
    "SearchResultsAnswer",
    "Thing",
    "WebPage",
    "ErrorCode",
    "ErrorSubCode",
    "Freshness",
    "ImageAspect",
    "ImageColor",
    "ImageContent",
    "ImageLicense",
    "ImageSize",
    "ImageType",
    "SafeSearch",
    "XBingApisSDK",
]
