# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6320, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Answer
    from ._models_py3 import Article
    from ._models_py3 import CreativeWork
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse
    from ._models_py3 import Identifiable
    from ._models_py3 import ImageObject
    from ._models_py3 import MediaObject
    from ._models_py3 import News
    from ._models_py3 import NewsArticle
    from ._models_py3 import NewsTopic
    from ._models_py3 import Organization
    from ._models_py3 import Query
    from ._models_py3 import Response
    from ._models_py3 import ResponseBase
    from ._models_py3 import SearchResultsAnswer
    from ._models_py3 import Thing
    from ._models_py3 import TrendingTopics
    from ._models_py3 import VideoObject
except (SyntaxError, ImportError):
    from ._models import Answer  # type: ignore
    from ._models import Article  # type: ignore
    from ._models import CreativeWork  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import Identifiable  # type: ignore
    from ._models import ImageObject  # type: ignore
    from ._models import MediaObject  # type: ignore
    from ._models import News  # type: ignore
    from ._models import NewsArticle  # type: ignore
    from ._models import NewsTopic  # type: ignore
    from ._models import Organization  # type: ignore
    from ._models import Query  # type: ignore
    from ._models import Response  # type: ignore
    from ._models import ResponseBase  # type: ignore
    from ._models import SearchResultsAnswer  # type: ignore
    from ._models import Thing  # type: ignore
    from ._models import TrendingTopics  # type: ignore
    from ._models import VideoObject  # type: ignore

from ._news_search_client_enums import (
    ErrorCode,
    ErrorSubCode,
    Freshness,
    SafeSearch,
    TextFormat,
    XBingApisSDK,
)

__all__ = [
    'Answer',
    'Article',
    'CreativeWork',
    'Error',
    'ErrorResponse',
    'Identifiable',
    'ImageObject',
    'MediaObject',
    'News',
    'NewsArticle',
    'NewsTopic',
    'Organization',
    'Query',
    'Response',
    'ResponseBase',
    'SearchResultsAnswer',
    'Thing',
    'TrendingTopics',
    'VideoObject',
    'ErrorCode',
    'ErrorSubCode',
    'Freshness',
    'SafeSearch',
    'TextFormat',
    'XBingApisSDK',
]
