# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Black
permissions:
  pull-requests: read


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo "PYTHONPATH=." >> "$GITHUB_ENV"

    - name: Checking the code for formatting issues
      run: |
          black --check --verbose $(git ls-files '*.py')
        
