# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Check for Copyright Headers

on:
  push:
    branches:
      - v-ghajam/open-source-compliance-copyright-headers-check
      - main
  pull_request:
    branches:
      - main

jobs:
  copyright-headers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
            
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install git
        sudo apt install fd-find ripgrep

    - name: Checking .yml files for copyright headers
      run: |
          count=$(git ls-files '*.yml' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.yml') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.yml') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            exit 1
          fi

    - name: Checking .cfg files for copyright headers
      run: |
          count=$(git ls-files '*.cfg' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.cfg') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.cfg') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            exit 1
          fi
      
    - name: Checking .md files for copyright headers
      run: |
          count=$(git ls-files '*.md' | wc -l)
          count1=$(grep -Fx '<!-- Copyright (c) Microsoft Corporation.' $(git ls-files '*.md') | wc -l)
          count2=$(grep -Fx ' Licensed under the MIT License. -->' $(git ls-files '*.md') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            exit 1
          fi

    - name: Checking .py files for copyright headers
      run: |
          count=$(git ls-files '*.py' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.py') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.py') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            exit 1
          fi
