# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Check for Copyright Headers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  copyright-headers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
            
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install git
        sudo apt install fd-find ripgrep

    - name: Checking .yml files for copyright headers
      run: |
          count=$(git ls-files '*.yml' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.yml') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.yml') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.yml')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.yml')
            exit 1
          fi

    - name: Checking .cfg files for copyright headers
      run: |
          count=$(git ls-files '*.cfg' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.cfg') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.cfg') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.cfg')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.cfg')
            exit 1
          fi
      
    - name: Checking .md files for copyright headers
      run: |
          count=$(git ls-files '*.md' | wc -l)
          count1=$(grep -Fx '<!-- Copyright (c) Microsoft Corporation.' $(git ls-files '*.md') | wc -l)
          count2=$(grep -Fx ' Licensed under the MIT License. -->' $(git ls-files '*.md') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '<!-- Copyright (c) Microsoft Corporation.' $(git ls-files '*.md')
            grep -LFx ' Licensed under the MIT License. -->' $(git ls-files '*.md')
            exit 1
          fi

    - name: Checking .py files for copyright headers
      run: |
          count=$(git ls-files '*.py' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.py') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.py') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.py')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.py')
            exit 1
          fi

    - name: Checking .toml files for copyright headers
      run: |
          count=$(git ls-files '*.toml' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.toml') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.toml') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.toml')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.toml')
            exit 1
          fi

    - name: Checking *requirements.txt files for copyright headers
      run: |
          count=$(git ls-files '*requirements.txt' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*requirements.txt') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*requirements.txt') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*requirements.txt')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*requirements.txt')
            exit 1
          fi

    - name: Checking .typed files for copyright headers
      run: |
          count=$(git ls-files '*.typed' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.typed') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.typed') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.typed')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.typed')
            exit 1
          fi

    - name: Checking .example files for copyright headers
      run: |
          count=$(git ls-files '*.example' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.example') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.example') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.example')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.example')
            exit 1
          fi
  
    - name: Checking .gitignore files for copyright headers
      run: |
          count=$(git ls-files '*.gitignore' | wc -l)
          count1=$(grep -Fx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.gitignore') | wc -l)
          count2=$(grep -Fx '# Licensed under the MIT License.' $(git ls-files '*.gitignore') | wc -l)
          if (( $count != $count1 || $count != count2))
          then
            echo 'Files with no copyright headers:'
            grep -LFx '# Copyright (c) Microsoft Corporation.' $(git ls-files '*.gitignore')
            grep -LFx '# Licensed under the MIT License.' $(git ls-files '*.gitignore')
            exit 1
          fi
